# fly.toml app configuration file generated for ai-engine-lingering-feather-7082 on 2025-05-19T15:00:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-engine-lingering-feather-7082'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  # Health check - use a simple endpoint that doesn't require auth
  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = "10s"
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
