# fly.toml app configuration file generated for ai-engine-lingering-feather-7082 on 2025-05-19T15:00:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-engine-lingering-feather-7082'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  # Optimized health check settings
  [[http_service.checks]]
    grace_period = "30s"        # Allow longer startup time
    interval = "10s"            # Check every 10 seconds
    method = "GET"
    path = "/health"            # Use dedicated health endpoint
    protocol = "http"
    restart_limit = 3           # Allow 3 failures before restart
    timeout = "5s"              # Shorter timeout for health checks
    tls_skip_verify = false

# Updated VM configuration for Redis queue workers
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "2gb"  # Increased memory for worker processes

# Environment variables
[env]
  # Number of worker processes to run
  WORKER_COUNT = "2"
  # Set to production for optimized Redis connection usage
  ENV = "production"
